# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 355afbf35f18d469c5d339612d0754af1129c565887d4966858da39dfdd9cc4d1b71bfad4e87f7c89a5ea985ca118646a762f7002f9f20b2ff3d600c8d41780d

test:
  secret_key_base: fa9ad4d2ecc274b93ac348c8b30f9d304470c42f4a5749c8a0259e3ec5cd2391ea10ad61e07f7fab04889f3ab2e4de04e8c3df9165fe47697dc4a2fd29f92f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
